apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::286940590014:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6T6GR4K8PNIC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::286940590014:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-13T09:35:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1308"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2076f072-2461-4889-8c21-23ea7e6c1a99
